<a href="https://colab.research.google.com/github/esay2077/bigdata_analysis/blob/main/Day1_python_ch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Go to Hell")

Go to Hell


In [ ]:
str1 = "python"
str2 = "programming"
print(str1+str2)
print(str1*2)

pythonprogramming
pythonpython


In [ ]:
str= "python programming"
print(str[0],str[1],str[4])
print(str[0:4])
print(str[5:9])

p y o
pyth
n pr


In [ ]:
print('오늘은 %d일 입니다.'%13) #정수
print("오늘은 %s 입니다."%"수요일") #문자열
print("지금 온도는 %f도 입니다."%32.7)#실수
print("지금 온도는 %0.2f 입니다."%32.8) #소수점 2번째 자리 까지 출력

오늘은 13일 입니다.
오늘은 수요일 입니다.
지금 온도는 32.700000도 입니다.
지금 온도는 32.80 입니다.


In [ ]:
str = "python programming" #특정문자 개수 세기
str.count('p')

2

In [ ]:
"/".join("python programming") #문자열 삽입

'p/y/t/h/o/n/ /p/r/o/g/r/a/m/m/i/n/g'

In [ ]:
str = "python programming" # 찾는 문자 처음 나온 위치 반환
str.find('m')

13

In [ ]:
str = "Python programming" #대문자
str.upper()

'PYTHON PROGRAMMING'

In [ ]:
str = "PYTHON PROGRAMMING" #소문자
str.lower()

'python programming'

In [ ]:
str = "python programming" #특정 문자 치환
str.replace("python","java")

'java programming'

In [ ]:
str = "python programming" #공백/특정문자 기준 문자 분리
str.split("n")
str.split()

['python', 'programming']

In [ ]:
a=10
b=3
print(a/b) #나누기
print(a//b) #몫
print(a%b) #나머지
print(a**b) #거듭제곱(10의 3승)

3.3333333333333335
3
1
1000


In [ ]:
print(a<b)
print(a>=b)
print(a<=b)
print(a==b)
print(a!=b)

True
False
True
False
True


In [ ]:
print(a and b) #둘다 참인가
print(a or b) # 둘중 하나라도 참인가
print(not a) # 반대

2
1
False


In [ ]:
a=100
a+=10
a-=10
a*=10
a/=10

In [ ]:
a= 10
if(a<0) :
    print('a는 음의 정수 입니다.')
print(a)

10


In [ ]:
if (a>0):
    print('a는 %d' %a)
    print("a는 양수")
else :
    print('a는 %d' %a)
    print("a는 음수")

a는 10
a는 양수


In [ ]:
if a>0 :
    print("a는 양의 정수")
elif a==0 :
    print("a는 0")
else:
    print('a는 음의 정수')

a는 양의 정수


In [ ]:
a = int(input("첫번째 수를 입력하세요"))
b = int(input("두번째 수를 입력하세요"))
c = int(input("세번째 수를 입력하세요"))

if a>=b:
    big = a
else:
    big = b

if c>=big:
    print("가장 큰수는 %d" %c)
else :
    print("가장 큰수는 %d" %big)

첫번째 수를 입력하세요45
두번째 수를 입력하세요46
세번째 수를 입력하세요34
가장 큰수는 46


In [ ]:
for i in range(5) :
    print("python programming")

python programming
python programming
python programming
python programming
python programming


In [ ]:
sum = 0

for i in range(1,6) :
    sum += i # sum = sum+i
    print("i의 값:%d, 합계: %d"%(i, sum))

i의 값:1, 합계: 1
i의 값:2, 합계: 3
i의 값:3, 합계: 6
i의 값:4, 합계: 10
i의 값:5, 합계: 15


In [ ]:
for i in range(1,10,2):
    print(i, end=' ')

1 3 5 7 9 

In [ ]:
for x in "python" :
    print(x)

p
y
t
h
o
n


In [ ]:
for i in range(1,9) : #구구단 출력
    for j in range(1,9):
        print(i*j, end = ' ')
    print()

1 2 3 4 5 6 7 8 
2 4 6 8 10 12 14 16 
3 6 9 12 15 18 21 24 
4 8 12 16 20 24 28 32 
5 10 15 20 25 30 35 40 
6 12 18 24 30 36 42 48 
7 14 21 28 35 42 49 56 
8 16 24 32 40 48 56 64 


In [ ]:
for i in range(2,10):
    for j in range(1,10):
        print("%d*%d=%d" %(i,j,i*j), end=' ')
    print()

2*1=2 2*2=4 2*3=6 2*4=8 2*5=10 2*6=12 2*7=14 2*8=16 2*9=18 
3*1=3 3*2=6 3*3=9 3*4=12 3*5=15 3*6=18 3*7=21 3*8=24 3*9=27 
4*1=4 4*2=8 4*3=12 4*4=16 4*5=20 4*6=24 4*7=28 4*8=32 4*9=36 
5*1=5 5*2=10 5*3=15 5*4=20 5*5=25 5*6=30 5*7=35 5*8=40 5*9=45 
6*1=6 6*2=12 6*3=18 6*4=24 6*5=30 6*6=36 6*7=42 6*8=48 6*9=54 
7*1=7 7*2=14 7*3=21 7*4=28 7*5=35 7*6=42 7*7=49 7*8=56 7*9=63 
8*1=8 8*2=16 8*3=24 8*4=32 8*5=40 8*6=48 8*7=56 8*8=64 8*9=72 
9*1=9 9*2=18 9*3=27 9*4=36 9*5=45 9*6=54 9*7=63 9*8=72 9*9=81 


In [ ]:
i = 1
while i <= 5:
    print("python programming")
    i +=1

python programming
python programming
python programming
python programming
python programming


In [ ]:
sum = 0
i = 1
while i <=10:
    sum += i
    print("i의 값: %d, 합계: %d" %(i, sum))
    i +=1

i의 값: 1, 합계: 1
i의 값: 2, 합계: 3
i의 값: 3, 합계: 6
i의 값: 4, 합계: 10
i의 값: 5, 합계: 15
i의 값: 6, 합계: 21
i의 값: 7, 합계: 28
i의 값: 8, 합계: 36
i의 값: 9, 합계: 45
i의 값: 10, 합계: 55


In [ ]:
i = 0
s = "python programming"

while i <= (len(s) - 1): #문자 인덱스는 0부터 시작하므로 1을 뺀다
    print(s[i], end =' ')
    i +=1

p y t h o n   p r o g r a m m i n g 

In [ ]:
i = 0
while i < 100:
    print(i,end=' ')
    i +=1
    if i ==10 :
        break

0 1 2 3 4 5 6 7 8 9 

In [ ]:
a = [70,80,90]
sum = 0
avg = 0

for x in a:
    sum +=x

student = len(a)
avg = sum/student
print("평균은 %f " %avg)

평균은 80.000000 


In [ ]:
a = [10,20,30,40]

sum = 0
avg = 0

i = 0
while i < len(a):
    sum += a[i]
    i+=1

avg = sum/len(a)
print("평균: %d" %avg)

평균: 25


In [ ]:
a = [4,5,6]
b = [1,2,3]
c = ["apple"]
d = [1,2,"apple"]

In [ ]:
print(b)
print(b[1],b[-1], b[1]+b[-1])

[1, 2, 3]
2 3 5


In [ ]:
print(a+b)
print(a*3)

[4, 5, 6, 1, 2, 3]
[4, 5, 6, 4, 5, 6, 4, 5, 6]


In [ ]:
a = ['a','b','c']

a.append('d')
print(a)

['a', 'b', 'c', 'd']


In [ ]:
a.insert(1,'aa') # 1번 위치에 aa 추가
print(a)

['a', 'aa', 'b', 'c', 'd']


In [ ]:
a= ['a', 'b', 'c','d','e']
a[2]= 'f'
print(a)

['a', 'b', 'f', 'd', 'e']


In [ ]:
del a[2]
print(a)

['a', 'b', 'd', 'e']


In [ ]:
a.reverse()
print(a)

['e', 'd', 'b', 'a']


In [ ]:
print(a.index('b'))

2


In [ ]:
a.sort()
print(a)

['a', 'b', 'd', 'e']


In [ ]:
print(a.index("b"))

1


In [ ]:
a = [10,20,30,40,50,60,30,4,50,40,60]

print(a.count(30))

2


In [ ]:
a.remove(30)
print(a)

[10, 20, 40, 50, 60, 30, 4, 50, 40, 60]


In [ ]:
a = ['a','b','c']
for x in a:
    print(x, end =" ")

a b c 

In [ ]:
i = 0
while i < len(a) :
    print(a[i], end = " ")
    i +=1

a b c 

In [ ]:
scores = [[1,2],[3,4],[5,6]]

print(scores[0][0])
print(scores[0][1])
print(scores[2][0])

1
2
5


In [ ]:
t = ('a',"b",'c','d') # tupple

print(t[0])
print(t[2:])
print(t * 2)
print(len(t))

a
('c', 'd')
('a', 'b', 'c', 'd', 'a', 'b', 'c', 'd')
4


In [ ]:
dict1 = {1:'a', 2:'b', 3:'c'}
dict2 = {'name':'python', 'age':'25', 'job':'programmer'}

print(dict1[1])
print(dict2['name'])

a
python


In [ ]:
dict1[5] ='f'
print(dict1)

{1: 'a', 2: 'b', 3: 'c', 5: 'f'}


In [ ]:
dict2['contact']='python.org'
print(dict2)

{'name': 'python', 'age': '25', 'job': 'programmer', 'contact': 'python.org'}


In [ ]:
print(dict2.keys())
print(dict2.values())
print(dict2.items())

if 'age' in dict2 :
    print(dict2.get('age'))

dict_keys(['name', 'age', 'job', 'contact'])
dict_values(['python', '25', 'programmer', 'python.org'])
dict_items([('name', 'python'), ('age', '25'), ('job', 'programmer'), ('contact', 'python.org')])
25


In [2]:
id_pass = {'cuk':"12ab",'python':'11aa','bigdaata':'cc21'}

id = input('사용자 아이디 입력하세요:')
password = input('비밀번호를 입력하세요:')

if id in id_pass:
    if password == id_pass.get(id) :
        print('아이디와 비밀번호가 맞습니다')
    else :
        print('비밀번호가 없습니다')
else :
    print('아이디가 존재하지 않습니다')

사용자 아이디 입력하세요:cuk
비밀번호를 입력하세요:123
비밀번호가 없습니다


In [4]:
def sum(a,b):
    return a + b

a=10
b=11
print(sum(a,b))

21


In [6]:
def f1(x) :
    if x % 2 == 0:
        return('짝수')
    else :
        return("홀수")

x = int(input("숫자를 입력"))

print("%d은 %s입니다"%(x,f1(x)))


숫자를 입력3431
3431은 홀수입니다


In [9]:
def f2 (x,y):
    mul = x*y
    return mul
x = int(input("숫자를 입력"))
y = int(input("숫자를 입력"))
print("두수의 곲은 %d"%f2(x,y))

숫자를 입력2
숫자를 입력3
두수의 곲은 6


In [11]:
import numpy as np

In [14]:
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([[1,2,3],[4,5,6]])

print(ar1)
print(ar2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [18]:
ar3 = np.random.randn(3)
ar4 = np.random.randn(2,3) #(행,열)

print(ar3)
print(ar4)

[-1.08540725 -1.16823928 -1.47076534]
[[ 1.20164778 -0.02514429 -2.29613741]
 [-1.1990832  -1.03572145  0.83897839]]


In [19]:
ar5 = np.zeros(5)
ar6 = np.ones((2,3))

print(ar5)
print(ar6)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
ar7 = np.arange(20, 200, 10)
ar8 = ar7.reshape(3,6)

print(ar7)
print(ar8)

[ 20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180 190]
[[ 20  30  40  50  60  70]
 [ 80  90 100 110 120 130]
 [140 150 160 170 180 190]]


In [24]:
ar1 = np.arange(1,21,1)
print(ar1)
print(ar1[1])

ar2 = ar1.reshape(2,10)
print(ar2)

ar2[1][1] = 100
print(ar2[1][0], ar2[1][1], ar2[1][2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
11 100 13


In [26]:
ar1 = np.arange(1,11,1)
ar2 = ar1 + 3
ar3 = ar1 * 2

print(ar1)
print(ar2,"\n", ar3)

[ 1  2  3  4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10 11 12 13] 
 [ 2  4  6  8 10 12 14 16 18 20]


In [32]:
ar1 = np.array([[5,7,9],[-7,-6,-19],[6,9,11]])

print(ar1)
print(ar1.sum())
print(ar1.mean())
print(ar1.max())
print(ar1.min())

print(ar1.max(axis=0)) #각 세로열 원소중 가장 큰값
print(ar1.max(axis=1)) #각 가로행 원소중 가장 큰값

[[  5   7   9]
 [ -7  -6 -19]
 [  6   9  11]]
15
1.6666666666666667
11
-19
[ 6  9 11]
[ 9 -6 11]


In [34]:
ar1 = np.array([[5,7,9],[-7,-6,-19],[6,9,11]])

print(ar1>0) # 참거짓
m_count = (ar1 < 0).sum() #0보다 작은 개수
print(m_count)

ar2 = np.where(ar1 < 0 , 0 , ar1) # 0보다 작은 원소는 0으로 대체
print(ar2)

[[ True  True  True]
 [False False False]
 [ True  True  True]]
3
[[ 5  7  9]
 [ 0  0  0]
 [ 6  9 11]]


In [41]:
ar1 = np.array([[5,7,9],[-3,-6,19],[6,4,11]])
print(ar1)

ar1.sort(0) #세로열 오름차순 정렬
print(ar1)

ar1.sort(1) #가로행 오름차순 정렬
print(ar1)

[[ 5  7  9]
 [-3 -6 19]
 [ 6  4 11]]
[[-3 -6  9]
 [ 5  4 11]
 [ 6  7 19]]
[[-6 -3  9]
 [ 4  5 11]
 [ 6  7 19]]


In [42]:
import pandas as pd

In [43]:
sr1 = pd.Series([10,30,20,40,70])
print(sr1)

0    10
1    30
2    20
3    40
4    70
dtype: int64


In [45]:
sr1 = pd.Series([1,2,3,4,5])
print(sr1.values) # 시리즈 값
print(sr1.index) # 인덱스 처음 마지막 증가 값
print(sr1[2]) # 인덱스 2

[1 2 3 4 5]
RangeIndex(start=0, stop=5, step=1)
3


In [59]:
sr1 = pd.Series([1,2,3,4,5], index = ['a','b','c','d','e']) #2차원 배열
print(sr1)
print(sr1[[1]]) #[[]] 2차원 구조
print(sr1[[0,1]]) #sr1의 인덱스 0번째, 1번째 값
print(sr1[['a','c']])

a    1
b    2
c    3
d    4
e    5
dtype: int64
b    2
dtype: int64
a    1
b    2
dtype: int64
a    1
c    3
dtype: int64


In [61]:
sr1 = pd.Series([10,20,30,40,60], index = ['a','b','c','d','e'])

print(sr1[1:4]) #인덱스 1부터 4
print(sr1['b':'d'])

b    20
c    30
d    40
dtype: int64
b    20
c    30
d    40
dtype: int64


In [62]:
df1 = pd.DataFrame([[10,20,30],[40,50,60]])

print(df1) # 가로 2행, 세로 3열, 인덱스(0,1), 속성명(0,1,2)

    0   1   2
0  10  20  30
1  40  50  60


In [67]:
dic1 = {'fruit':['사과','배','감','귤','바나나'],
        'price':[100,200,150,50,200],
        'qty':[10,25,30,20,15]}

df1 = pd.DataFrame(dic1)
print(dic1)

{'fruit': ['사과', '배', '감', '귤', '바나나'], 'price': [100, 200, 150, 50, 200], 'qty': [10, 25, 30, 20, 15]}


In [69]:
df1 = pd.DataFrame(dic1,index= ['a','b','c','d','e'])
print(df1)

  fruit  price  qty
a    사과    100   10
b     배    200   25
c     감    150   30
d     귤     50   20
e   바나나    200   15


In [70]:
df1.rename(columns= {'fruit':'과일','price':'가격','qty':'수량'}, inplace= True) #세로열 이름 변경
df1.rename(index = {'a':'01','b':'02','c':'03','d':'04','e':'05'}, inplace = True) #inplace 객체 재사용 , 가로행
print(df1)

     과일   가격  수량
01   사과  100  10
02    배  200  25
03    감  150  30
04    귤   50  20
05  바나나  200  15


In [74]:
df1 = pd.read_csv('/content/df_sample.csv')
df1

학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12
5  S06  71  75   16  16
6  S07  60  80   18  18
7  S08  72  65   14  14
8  S09  65  65   14  14
9  S10  85  78   10  10

In [75]:
df1.head(5)

학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12

In [76]:
df1.shape

(10, 5)

In [77]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   학번      10 non-null     object
 1   중간      10 non-null     int64 
 2   기말      10 non-null     int64 
 3   리포트     10 non-null     int64 
 4   퀴즈      10 non-null     int64 
dtypes: int64(4), object(1)
memory usage: 528.0+ bytes


In [78]:
df1.describe(include='all')

학번         중간         기말        리포트         퀴즈
count    10  10.000000  10.000000  10.000000  10.000000
unique   10        NaN        NaN        NaN        NaN
top     S01        NaN        NaN        NaN        NaN
freq      1        NaN        NaN        NaN        NaN
mean    NaN  77.600000  78.500000  15.000000  15.000000
std     NaN  10.616549   9.663793   3.559026   3.559026
min     NaN  60.000000  65.000000  10.000000  10.000000
25%     NaN  71.250000  75.000000  12.500000  12.500000
50%     NaN  79.000000  78.000000  15.000000  15.000000
75%     NaN  84.250000  82.250000  18.000000  18.000000
max     NaN  93.000000  95.000000  20.000000  20.000000

In [81]:
df1['중간'].mean()
df1[['중간','기말']].mean()

중간    77.6
기말    78.5
dtype: float64

In [88]:
print(df1['중간'].min())
print(df1[['중간','기말']].max())


60
중간    93
기말    95
dtype: int64


In [89]:
print(df1['중간'].median())

79.0


In [91]:
print('표준편차:')
print(df1[['중간','기말']].std())

print('분산:')
print(df1[['중간','기말']].var())

표준편차:
중간    10.616549
기말     9.663793
dtype: float64
분산:
중간    112.711111
기말     93.388889
dtype: float64


In [94]:
df1['퀴즈'].value_counts()

퀴즈
18    3
10    2
14    2
20    1
12    1
16    1
Name: count, dtype: int64