<a href="https://colab.research.google.com/github/esay2077/bigdata_analysis/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC%EC%9D%84_%ED%99%9C%EC%9A%A9%ED%95%9C_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%BF%A1%EB%B6%81_1%EC%9E%A5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# 벡터 만들기
import numpy as np

vector_row = np.array([1,2,3])

vector_coloum = np.array([[1],[2],[3]])

print(type(vector_row))

<class 'numpy.ndarray'>


In [3]:
bad_way = np.ndarray((3,)) # 권장 안함

In [4]:
new_row = np.asarray([1,2,3])

new_row = np.asarray(vector_row)

new_row is vector_row


True

In [5]:
new_row = np.array(vector_row)
new_row is vector_row


False

In [6]:
new_row = vector_row.copy()
new_row is vector_row

False

In [7]:
# 행렬 만들기
import numpy as np
matrix = np.array([[1,2],[1,2],[1,2]])

matrix_object = np.mat([[1,2],[1,2],[1,2]])
matrix
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [8]:
zero_matrix = np.zeros((3,2))
zero_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
one_matrix = np.ones((3,2))
one_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
seven_matrix = np.zeros((3,2)) + 7
seven_matrix

array([[7., 7.],
       [7., 7.],
       [7., 7.]])

In [11]:
seven_matrix = np.full((3,2),7) # 효율
seven_matrix

array([[7, 7],
       [7, 7],
       [7, 7]])

In [12]:
# 희소 행렬 만들기

import numpy as np
from scipy import sparse

matrix = np.array([[0,0],
                   [0,1],
                    [3,0]])
matrix_sparse = sparse.csr_matrix(matrix) # sparse 희소
# sparse matrix 또는 sparse array는 행렬의 대부분의 요소가 0인 행렬입니다.
# 반대로 대부분의 요소가 0이 아니면 행렬은 dense하다고 표현합니다.
# 값이 0 인 갯수를 전체 값의 총 수로 나눈 값 (예 : m × n 행렬의 경우 m × n)을 행렬의 희소성 또는 sparsity 라고합니다.
print(matrix_sparse)


  (1, 1)	1
  (2, 0)	3


In [13]:
matrix_large = np.array([[0,0,0,0,0,0,0,0,0],
                         [0,1,0,0,0,0,0,0,0],
                         [3,0,0,0,0,0,0,0,0]])
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_sparse)
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3
  (1, 1)	1
  (2, 0)	3


In [14]:
matrix_sparse_2 = sparse.csr_matrix(([1,3],([1,2],[1,0])), shape =(3,10))

print(matrix_sparse_2)

  (1, 1)	1
  (2, 0)	3


In [15]:
print(matrix_sparse_2.toarray()) #희소행렬 -> 밀집행렬

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]


In [16]:
matrix_sparse_2.todense() #np.matrix 객체 반환

matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
# 원소 선택하기
import numpy as np

vector = np.array([1,2,3,4,5,6])

matrix = np.array([[1,2,3],
                   [4,5,6],
                    [7,8,9]])
vector[2]

3

In [18]:
matrix[1,1]

5

In [19]:
vector[:] #전체

array([1, 2, 3, 4, 5, 6])

In [20]:
vector[:3] #0~3까지

array([1, 2, 3])

In [21]:
vector[3:] # 3 이후 ~ 끝

array([4, 5, 6])

In [22]:
vector[-1] # 마지막 원소

6

In [23]:
matrix[:,1:2] # 모든 행, 두번째 열

array([[2],
       [5],
       [8]])

In [24]:
matrix[[0,2]] # 인덱싱

array([[1, 2, 3],
       [7, 8, 9]])

In [25]:
matrix[[0,2],[1,0]]

array([2, 7])

In [26]:
mask = matrix >5

mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [27]:
matrix[mask]

array([6, 7, 8, 9])

In [28]:
import numpy as np

matrix = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])

matrix.shape # 3행 4열

(3, 4)

In [29]:
matrix.size

12

In [30]:
matrix.ndim

2

In [31]:
print(matrix.dtype)

int64


In [33]:
print(matrix.itemsize)

8


In [34]:
print(matrix.nbytes)

96


In [35]:
# 백터화 연산 적용하기

import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

add_100 = lambda i: i+100 # 100을 더하는 함수

vectorized_add_100 = np.vectorize(add_100) # 벡터화 된 함수

vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [36]:
matrix + 100 #브로드캐스팅

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [37]:
matrix + [100, 100, 100]

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [38]:
matrix + [100,100,100]

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [39]:
matrix + [[100],[100],[100]]

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [40]:
# 최댓값, 최솟값 찾기

import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
np.max(matrix)


9

In [41]:
np.min(matrix)

1

In [43]:
np.max(matrix, axis = 0) # 열에서 최댓값

array([7, 8, 9])

In [44]:
np.min(matrix, axis = 1) # 행에서 최솟값

array([1, 4, 7])

In [45]:
vector_column = np.max(matrix, axis = 1, keepdims = True) # 원본 차원과 동일한 결과
vector_column

array([[3],
       [6],
       [9]])

In [46]:
matrix - vector_column # 브로드 캐스팅

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [47]:
# 평균, 분산, 표준편차 계산
# mean, var, std 함수 사용

import numpy as np

matrix = np.array([[1,2,3,],[4,5,6],[7,8,9]])

np.mean(matrix)

5.0

In [49]:
round(np.var(matrix),2)

6.67

In [50]:
round(np.std(matrix),2)

2.58

In [51]:
np.mean(matrix, axis = 0) # 열의 평균
# axis = 0 열 (세로)
# axis = 1 행 (가로)


array([4., 5., 6.])

In [52]:
np.std(matrix, ddof = 1)

2.7386127875258306

In [53]:
import pandas as pd

df = pd.DataFrame(matrix.flatten())
df.std()

0    2.738613
dtype: float64

In [55]:
# 배열 크기 바꾸기
import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [10,11,12]])
# 4 * 3 행열
matrix.reshape(2,6)
# 2 * 6 행열

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [56]:
matrix.size

12

In [60]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [58]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [61]:
matrix.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [62]:
matrix.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [63]:
# 백터나 행렬 전치하기
import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matrix.T # 전치: 행렬의 행과 열을 서로 맞바꾼 행렬을 '전치행렬(transposed matrix)'

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [64]:
np.array([1,2,3,4,5,6]).T
# 벡터 전치

array([1, 2, 3, 4, 5, 6])

In [65]:
np.array([[1,2,3,4,5,6]]).T
# 행 벡터 전치 - > 열 벡터 전환

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [66]:
matrix.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [68]:
matrix = np.array([[[1,2],
                    [3,4],
                    [5,6]],

                   [[7,8],
                    [9,10],
                    [11,12]]])
# 2 * (3 * 2) 행렬
matrix.transpose((0,2,1))
# 두번째와 세번째 차원 변경 2 * (2 * 3)

array([[[ 1,  3,  5],
        [ 2,  4,  6]],

       [[ 7,  9, 11],
        [ 8, 10, 12]]])

In [75]:
# 행렬 펼치기

import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

matrix.flatten() # 행렬 1차원 배열 변환

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
matrix.reshape(1,-1) # 행 벡터

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [77]:
vector_reshaped = matrix.reshape(-1)
vector_flattened = matrix.flatten()

matrix[0][0] = -1 # (0,0) 위치의 원소를 바꿈 1 -> -1

vector_reshaped

array([-1,  2,  3,  4,  5,  6,  7,  8,  9])

In [78]:
vector_flattened
# 반영 안됨

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
# 행렬의 랭크 구하기 (차원)

import numpy as np

matrix = np.array([[1,1,1],
                   [1,1,10],
                   [1,1,15]])
# 차원 반환
np.linalg.matrix_rank(matrix) # 특잇값 분해

2

In [81]:
s = np.linalg.svd(matrix,compute_uv= False)
# svd함수로 특잇값만 계산
np.sum(s > 1e-10)

2

In [83]:
# 행렬식 계산하기
import numpy as np

matrix = np.array([[1,2,3],
                  [2,4,6],
                  [3,8,9]])
np.linalg.det(matrix) # 행렬식 det
# 행렬식 정방행렬에 의산 선형 변환의 특징을 나타내는 스칼라값

0.0

In [84]:
# 행렬의 대각 원소
# diagonal 메서드

import numpy as np

matrix = np.array([[1,2,3],
                   [2,4,6],
                   [3,8,9]])

matrix.diagonal() # 대각 원소 (주대각선)

array([1, 4, 9])

In [86]:
matrix.diagonal(offset = 1) # 주대각선 + 1 대각원소

array([2, 6])

In [87]:
matrix.diagonal(offset = -1) # 주대각선 - 1 대각원소

array([2, 8])

In [90]:
a = matrix.diagonal().copy()

a = np.diag(matrix)
print(a)

[1 4 9]


In [91]:
np.diag(a) #대각행렬

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

In [92]:
# 행렬의 대각합 계산
# trace

import numpy as np

matrix = np.array([[1,2,3],
                   [2,4,6],
                   [3,8,9]])

matrix.trace() #대각합 반환 1+4+9

14

In [93]:
sum(matrix.diagonal()) #대각원소의 합

14

In [94]:
matrix.trace(offset=1) # 주대각+1 합

8

In [95]:
matrix.trace(offset = -1)# 주대각 - 1 합

10

In [96]:
# 고윳값과 고유벡터 찾기
#linalg.eig

import numpy as np

matrix = np.array([[1,-1,3],
                   [1,1,6],
                   [3,8,9]])

eigenvalues, eignvenctors = np.linalg.eig(matrix)
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [97]:
eignvenctors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

In [98]:
matrix = np.array([[1,-1,3],
                   [-1,1,6],
                   [3,6,9]])
eignvalues, eignvectors = np.linalg.eigh(matrix) # 더빨리 계산

In [99]:
# 점곱 계산하기
# dot

import numpy as np

vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

np.dot(vector_a,vector_b) # 4 + 10 + 18

32

In [100]:
vector_a @ vector_b # 연산자 @ (스칼라 배열은 안됨)

32

In [105]:
# 행렬 덧셈과 뺄셈
# add, subtract

import numpy as np

matrix_a = np.array([[1,1,1],
                     [1,1,1],
                     [1,1,2]])

matrix_b = np.array([[1,3,1],
                    [1,3,1],
                    [1,3,8]])

np.add(matrix_a,matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [106]:

np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [108]:
# 행렬 곱셈

import numpy as np

matrix_a = np.array([[1,1],
                     [1,2]])
matrix_b = np.array([[1,3],
                     [1,2]])

np.dot(matrix_a,matrix_b)

array([[2, 5],
       [3, 7]])

In [109]:
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [110]:
# 역행렬
# inv
import numpy as np

matrix = np.array([[1,4],
                   [2,5]])

np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [111]:
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [112]:
#pinv
matrix = np.array([[1,4,7],
                   [2,5,8]])

np.linalg.pinv(matrix) #유사 역행렬

array([[-1.16666667,  1.        ],
       [-0.33333333,  0.33333333],
       [ 0.5       , -0.33333333]])

In [113]:
# 난수 생성
import numpy as np

np.random.seed(0)
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [114]:
np.random.randint(0,11,3)

array([3, 7, 9])

In [117]:
np.random.normal(0.0,1.0,3) # 평균 0.0 , 표준편차 1.0 정규분포 3개의 수

array([-1.42232584,  1.52006949, -0.29139398])

In [118]:
np.random.logistic(0.0,1.0,3) # 로지스틱 분포, 평균 0.0, 스케일 1.0

array([-0.98118713, -0.08939902,  1.46416405])

In [119]:
np.random.uniform(1.0,2.0,3) # 1보다 크고 2보다 작은 수

array([1.47997717, 1.3927848 , 1.83607876])

In [120]:
np.random.random_sample((2,3)) # 2행 3열 0~1 사이

array([[0.33739616, 0.64817187, 0.36824154],
       [0.95715516, 0.14035078, 0.87008726]])

In [121]:
np.random.rand(2,3) # np.random.random_sample 동일

array([[0.47360805, 0.80091075, 0.52047748],
       [0.67887953, 0.72063265, 0.58201979]])

In [122]:
np.random.randint(0,1,10) # 최솟값 이상 최댓값 미만 정수 난수 10개

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [123]:
np.random.standard_normal((2,3)) # mean 0 std 1 normal random seed
# np.random.normal(0.0,1.0,(2,3)) 동일

array([[-0.13309028,  1.59456053,  0.23043417],
       [-0.06491034, -0.96898025,  0.59124281]])

In [124]:
np.random.randn(2,3) # 매개변수로 전달
# np.random.normal(0.0,1.0,(2,3)) 동일

array([[-0.7827755 , -0.44423283, -0.34518616],
       [-0.88180055, -0.44265324, -0.5409163 ]])

In [125]:
np.random.choice([0,1,2],5) # 0,1,2 정수중 랜덤 하게 5번 뽑기
#np.random.choice(3,5) 동일

array([0, 1, 2, 2, 0])

In [126]:
a = np.array([0,1,2,3,4])
np.random.shuffle(a) # 섞기
a

array([0, 2, 3, 4, 1])

In [127]:
np.random.permutation(a)
# 복사본 생성후 섞음

array([2, 0, 1, 3, 4])

In [128]:
np.random.permutation(5)
# 정수 - 1 숫자 섞은 후 반환

array([4, 1, 2, 0, 3])